version: "3"
services:
    gitlab-notify-db:
        image: mysql
        restart: always
        environment:
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ./persistent-volume/gitlab-notify-db/db:/var/lib/mysql
        ports:
            - ${MYSQL_PORT}:3306
    gitlab-notify-phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - "${PHPMYADMIN_PORT}:80"
        links:
            - gitlab-notify-db:gitlab-notify-db
    gitlab-notify-callback:
        build: gitlab-notify-callback
        ports:
            - "${GITLAB_NOTIFY_CALLBACK_PORT}:8080"
        environment:
          LOGGING_LEVEL: ${LOGGING_LEVEL}
          LOG_FILE: ${LOG_PATH}/${LOG_FILE}
        volumes:
            - ./persistent-volume/gitlab-notify-callback/log:/${LOG_PATH}
    gitlab-notify-manager:
        build: gitlab-notify-manager
        links:
            - gitlab-notify-callback:gitlab-notify-callback
        depends_on:
            - gitlab-notify-callback
        environment:
          WAIT_HOSTS: gitlab-notify-db:${MYSQL_PORT}
          WAIT_SLEEP_INTERVAL: 5
          WAIT_HOSTS_TIMEOUT: 300
          OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
          OAUTH_SECRET_ID: ${OAUTH_SECRET_ID}
          OAUTH_ACCESS_TOKEN_URL: ${OAUTH_ACCESS_TOKEN_URL}
          OAUTH_AUTHORIZATION_URL: ${OAUTH_AUTHORIZATION_URL}
          OAUTH_USER_RESOURCE_URL: ${OAUTH_USER_RESOURCE_URL}
          GITLABLINE_CALLBACK_URL: http://gitlab-notify-callback:${GITLAB_NOTIFY_CALLBACK_PORT}
          HIBERNATE_DDL_AUTO: ${HIBERNATE_DDL_AUTO}
          DATASOURCE_URL: jdbc:mysql://gitlab-notify-db:${MYSQL_PORT}/${MYSQL_DATABASE}
          DATASOURCE_USERNAME: ${MYSQL_USER}
          DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
          LOGGING_LEVEL: ${LOGGING_LEVEL}
          LOG_FILE: ${LOG_PATH}/${LOG_FILE}
        volumes:
            - ./persistent-volume/gitlab-notify-manager/log:/${LOG_PATH}
        ports:
            - "${GITLAB_NOTIFY_MANAGER_PORT}:8080"      
volumes:
    gitlab-notify-db:
        driver: "local"
    gitlab-notify-callback:
        driver: "local"
    gitlab-notify-manager:
        driver: "local"